### ISSUE TITLE
Windows 10 - Kodi Nightly - script.module.pycryptodome not available

### ISSUE THREAD

**Issue by Eloque** [asciidisco/plugin.video.netflix#100]
Might not related to this plugin, but on this nightly ; https://kodi.mirror.wearetriple.com/nightlies/windows/win64/master/KodiSetup-20170820-7fd8f0b551-master-x64.exe

There is no pycryptodome available, nor can I manage to install in any way. Installing it with pip has no effect, as Kodi doesn't seem to use the Windows python.

**Comment by asciidisco** [comment]
It seems like there´s an issue with Python and Crypto related stuff on the Windows builds.
I don't have a Windows Testsystem, so I can't verify the problems. 

Closing this & linking to the existing thread, so that we can continue the discussion (and share fixes) in one thread: https://github.com/asciidisco/plugin.video.netflix/issues/85
