### ISSUE TITLE
Issue loading content

### ISSUE THREAD

**Issue by lwrcase** [asciidisco/plugin.video.netflix#148]
Just about an hour ago, I rebooted Kodi and was unable to load any content. The add-on seems to be able to log in and displays my main profile and I can navigate into it but trying to load "My List" or any other navigation items fails.

Kodi.6f99b6e
Inputstream.Adaptive.dde3921

A common theme for my issue seems to be <class 'httplib.BadStatusLine'>
Specifically:

16:04:34.960 T:140301579589376   ERROR:     if video['videoQuality']['hasHD']:
16:04:34.960 T:140301579589376   ERROR: KeyError: 'videoQuality'

https://pastebin.com/CiwXQZYm

**Comment by lwrcase** [comment]
I commented out lines 970-973 in resources/lib/NetflixSession.py as it seemed that the key "videoQuality" in he video object was not found and it's working again.

**Comment by hawkeyexp** [comment]
Fixed with latest pull request

**Comment by trummerjo** [comment]
Should be fixed with the new 0.11.25 version which includes hawkeyexp's pull request?

**Comment by lwrcase** [comment]
It has been fixed in version 0.11.25. Closing

**Comment by sikgerar** [comment]
I know this thread is closed, but I am having this same issue on:
Rpi2 
osmc 18 fresh install
netflix addon 0.12.1


---- log extract: ---
20:50:14.136 T:1957117952  NOTICE: m_playbackStarting
20:50:16.304 T:1578103792  NOTICE: Previous line repeats 2 times.
20:50:16.304 T:1578103792   ERROR: Traceback (most recent call last):
20:50:16.304 T:1578103792   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
20:50:16.304 T:1578103792   ERROR:     self.process_request(request, client_address)
20:50:16.304 T:1578103792   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
20:50:16.305 T:1578103792   ERROR:     self.finish_request(request, client_address)
20:50:16.305 T:1578103792   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
20:50:16.305 T:1578103792   ERROR:     self.RequestHandlerClass(request, client_address, self)
20:50:16.305 T:1578103792   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
20:50:16.305 T:1578103792   ERROR:     self.handle()
20:50:16.305 T:1578103792   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
20:50:16.305 T:1578103792   ERROR:     self.handle_one_request()
20:50:16.305 T:1578103792   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
20:50:16.305 T:1578103792   ERROR:     method()
20:50:16.305 T:1578103792   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpRequestHandler.py", line 58, in do_GET
20:50:16.305 T:1578103792   ERROR:     result = getattr(RES_HANDLER, method)(params)
20:50:16.305 T:1578103792   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpSubRessourceHandler.py", line 107, in login
20:50:16.305 T:1578103792   ERROR:     _ret = self.netflix_session.login(account=self.credentials)
20:50:16.306 T:1578103792   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/NetflixSession.py", line 289, in login
20:50:16.306 T:1578103792   ERROR:     content=page.text)
20:50:16.306 T:1578103792   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/NetflixSession.py", line 149, in extract_inline_netflix_page_data
20:50:16.306 T:1578103792   ERROR:     '"' + item + '":(.*?)"(.+?)"').findall(react_context[0])
20:50:16.306 T:1578103792   ERROR: IndexError: list index out of range
20:50:16.313 T:1533006832   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'httplib.BadStatusLine'>
                                            Error Contents: ''
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/addon.py", line 42, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 67, in router
                                                options = self.before_routing_action(params=params)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 544, in before_routing_action
                                                if self.establish_session(account=credentials) != True:
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 475, in establish_session
                                                return True if is_logged_in else self._check_response(self.call_netflix_service({'method': 'login', 'email': account['email'], 'password': account['password']}))
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 696, in call_netflix_service
                                                data = urllib2.urlopen(full_url).read()
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 431, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 449, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open
                                                r = h.getresponse(buffering=True)
                                              File "/usr/lib/python2.7/httplib.py", line 1111, in getresponse
                                                response.begin()
                                              File "/usr/lib/python2.7/httplib.py", line 444, in begin
                                                version, status, reason = self._read_status()
                                              File "/usr/lib/python2.7/httplib.py", line 408, in _read_status
                                                raise BadStatusLine(line)
                                            BadStatusLine: ''
                                            -->End of Python script error report<--
20:50:16.314 T:1957117952   ERROR: Playlist Player: skipping unplayable item: 6, path [plugin://plugin.video.netflix/?action=play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27writer%27%3A+%27%27%2C+%27episode%27%3A+5%2C+%27plot%27%3A+u%27Estalla+la+controversia+en+la+%5Cxfaltima+mitad+de+1944%2C+cuando+las+fuerzas+estadounidenses+y+brit%5Cxe1nicas+deciden+no+bombardear+Auschwitz.%27%2C+%27season%27%3A+1%2C+%27tvshowtitle%27%3A+u%27Auschwitz%27%2C+%27title%27%3A+u%27Murder+and+Intrigue%27%2C+%27mediatype%27%3A+u%27episode%27%2C+%27mpaa%27%3A+u%27-%27%2C+%27director%27%3A+%27%27%2C+%27genre%27%3A+u%27TV+brit%5Cxe1nica%27%2C+%27year%27%3A+2005%2C+%27duration%27%3A+2866%7D&video_id=70058197&pin=False&start_offset=2837]
20:50:16.314 T:1957117952  NOTICE: m_playbackStarting
20:50:16.345 T:1957117952  NOTICE: Previous line repeats 1 times.
20:50:16.345 T:1957117952 WARNING: CGUIWindowManager - HandleAction - ignoring action 92, because topmost modal dialog closing animation is running
21:42:58.737 T:1957117952  NOTICE: Storing total System Uptime

---

**Comment by lwrcase** [comment]
@sikgerar this looks to be a different issue than my original issue. the script is throwing an index out of range exception here:

20:50:16.306 T:1578103792 ERROR: File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/NetflixSession.py", line 149, in extract_inline_netflix_page_data
20:50:16.306 T:1578103792 ERROR: '"' + item + '":(.*?)"(.+?)"').findall(react_context[0])
20:50:16.306 T:1578103792 ERROR: IndexError: list index out of range

at object react_context index 0.

i would submit a new issue to have this looked into.
