### ISSUE TITLE
Audio track names Brazilian Portuguese on Netflix is named Unknown (or Desconhecido) on Kodi

### ISSUE THREAD

**Issue by matteozambon89** [asciidisco/plugin.video.netflix#271]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

Brazilian Portuguese audio title shows as `unk` on Kodi Remote and `Unknown` (when Kodi is on ENG) or `Desconhecido` (when Kodi is on PT-BR).

### Steps to Reproduce

1. Open whatever movie that supports Brazilian Portuguese
2. Change movie audio track

**Expected behavior:** 

1. Open whatever movie that supports Brazilian Portuguese
2. Change movie audio track to Brazilian Portuguese

**Actual behavior:** 

1. Open whatever movie that supports Brazilian Portuguese
2. Change movie audio track to Unknown

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

LibreElec with Kodi 18 (every movie works, it's just UI issue)

**Comment by Aimost** [comment]
Yep, same here.

here's an interesting fact: if I set a default language like English, then it saves the configuration. But my language appears as Unknown and doesn't work.

I tried leaving the GUI in English and selecting Spanish by default, but it still shows Spanish as Unknown.

**Comment by asciidisco** [comment]
There are 2 different problems here, one is a bug and can/will be solved (language not showing up in selection) and one is not a real bug, but rather an inconvenience the plugin can't do a thing about.

Both are already discussed here: https://github.com/asciidisco/plugin.video.netflix/issues/64
which is why I´m going to close this.

What can be done to have multiple defaults per Netflix profile is:
- Create Kodi profiles for each user
- Set the language defaults as mentioned in the above linked issue per profile
- Link the Netflix profile to the Kodi profile (can be done in the selection menu in the profile screen of the plugin)
- Switch the Kodi profile instead of just the Netflix profile in the future

**Comment by matteo-harpoon** [comment]
@asciidisco 

- **Create Kodi profiles for each user** My user is already set to Portuguese (Brazil)
- **Set the language defaults as mentioned in the above linked issue per profile** If I do that Kodi plugin won't run
- **Link the Netflix profile to the Kodi profile (can be done in the selection menu in the profile screen of the plugin)** I did that already but nothing changed
- **Switch the Kodi profile instead of just the Netflix profile in the future** I use always the same profile on Kodi and I never have to switch to another

I've attached some screenshots from [https://github.com/Sandmann79/xbmc](Sandmann79/xbmc) plugin which works with Amazon Prime, may be a good idea to take a look on how they are doing the Fallback and the other details.
I'm not fully aware of the Netflix API power but maybe something can be applied.

![screen shot 2018-01-23 at 13 26 58](https://user-images.githubusercontent.com/12065733/35284144-2de9541e-0041-11e8-846e-0bb231887c34.png)
![screen shot 2018-01-23 at 13 27 02](https://user-images.githubusercontent.com/12065733/35284145-2f83af86-0041-11e8-86a2-b68498630f0d.png)

**Comment by Uukrull** [comment]
I have a similar problem with castilian audio y subtitle tracks (Kodi doesn't seem to like the "es-ES" language code). I solved this eons ago by replacing this [line](https://github.com/asciidisco/plugin.video.netflix/blob/78b4d3a6397d1934476b61c8efbbde69756822ec/resources/lib/MSL.py#L475) with:

`        xml = xml.replace('es-ES', 'es').replace('\n', '').replace('\r', '')`

@matteo-harpoon: You should be able to the same with (I think):

`        xml = xml.replace('pt-BR', 'pt').replace('\n', '').replace('\r', '')`
