### ISSUE TITLE
[Playback] Video doesn't play, only gibberish

### ISSUE THREAD

**Issue by RenaKunisaki** [asciidisco/plugin.video.netflix#274]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

When selecting any video on Netflix, either it won't play at all, or it plays only flickering pink and green squares.

### Steps to Reproduce

1. Open Netflix
2. Select a video

**Expected behavior:** [What you expected to happen]

Video should play.

**Actual behavior:** [What actually happened]

Screen shows random colours or video doesn't play at all.

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

* Kodi 18.0-ALPHA1 (Jan 11 2018) on Raspberry Pi 3B, LibreELEC (Milhouse) devel-20180111220352-#0111-g883f1ba
* Skin: Xperience1080
* Canada

## Debug log

http://ix.io/E3r

**Comment by asciidisco** [comment]
Can´t pinpoint the problem, but could be an inputstream issue. @liberty-developer could you have a look at this?

**Comment by hauemric** [comment]
Very same issue here. I thing that even the recent bug report stating that the video playback does not start is related to the one described here.
After the Netflix Add-on stopped working (I had it working at first on my libreelec, Raspi 3B, Kodi 18 newest build), I wiped everything and re-installed.
It was working like a charm again. But when I started installing all the other Add-ons I use "ARD Mediathek", "DMAX mediathek", movie scrapers, open subtitles..., it stopped working again.
I can login and access the streams all ok. The problem is the video stream/playback.
I can start the video playback but it wont show. In Kodi 18, via the side menue, I force to show the playback screen but there the video wont show - there is just a black screen.
I can scrub through the video and the sound will play - still no video.
When I manually change the input stream resolution, I will get gibberish playback like mentioned in the other thread...
I deinstalled your Netflix Addon and reinstalled it. Same with the asci disco.
No positive results there...
Addon still working just video no playing (sound is there)...

Is there a way to completely de-install the asci disco and reinstall it?
Do other Add-ons somehow corrupt the Netflix dependencies?

Cheers and many thanks for this great Addon (hope mine will work again soon).

**Comment by hauemric** [comment]
Hey all,

sorry for the spam but I didn't want to repost and am wondering if there might have been a fix to the issue? It is probably something simply.

Best

**Comment by KidCoding** [comment]
I had some issues with the video playback in the Netflix plugin, Yoututbe and even sometimes when I was playing local files. A recent update of the Mulhouse's libreelec build has solved the problem. It is the build of the 4th of february. May be you should try.  Just put the tar in the /storage/.update and then reboot. I hope this will help.

**Comment by hauemric** [comment]
Hey,
Thanks for your hint. I updated to the newest built but it didn‘t fix the issue...

**Comment by jayMcoder** [comment]
@RenaKunisaki @hauemric 
Try the following fix from comments in #286 
Goto Settings -> Player -> Videos -> Under processing disable OMXPlayer
You can enable MMAL in-case if you need hardware acceleration for your other media playback.

**Comment by caphm** [comment]
I assume this issue has been resolved, as there has not been any further activity. Feel free to reopen if the issue still persists.

**Comment by vaguerant** [comment]
This issue is resolved in the sense that everything works as long as you disable omxplayer on Raspberry Pi (apologies, I have very little familiarity with recent Kodi builds on other platforms), but omxplayer is a valuable part of running Kodi on a Pi--albeit one that Kodi apparently plans to deprecate--as it's able to run smoothly on as low-spec a system as the Pi.

As such, I'm not really sure if "disable omxplayer" is an ideal solution, because outside of the Netflix addon, omxplayer is perfectly good to use and improves the "Kodi experience" for most Pi users.

The ideal solution, if it's possible, would be for the Netflix addon to refuse to play video using omxplayer and fall back to whatever else the system has available. I again apologize for having no idea if that's something that's currently possible via the Kodi addon system. If not, perhaps an issue for similar should be filed upstream at Kodi, because forcing users to change global settings to make individual addons work is suboptimal.
