### ISSUE TITLE
No module named Cryptodome.PublicKey

### ISSUE THREAD

**Issue by mihailescu2m** [asciidisco/plugin.video.netflix#36]
I get this error when starting kodi with the plugin installed.

Any idea how to fix it?

`20:31:34.362 T:2461196704   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named Cryptodome.PublicKey
                                            Traceback (most recent call last):
                                              File "/home/odroid/.kodi/addons/plugin.video.netflix/service.py", line 11, in <module>
                                                from resources.lib.MSLHttpRequestHandler import MSLHttpRequestHandler
                                              File "/home/odroid/.kodi/addons/plugin.video.netflix/resources/lib/MSLHttpRequestHandler.py", line 9, in <module>
                                                from MSL import MSL
                                              File "/home/odroid/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 17, in <module>
                                                from Cryptodome.PublicKey import RSA
                                            ImportError: No module named Cryptodome.PublicKey
                                            -->End of Python script error report<--
`

**Comment by whirm** [comment]
Try with `pip install pycryptodome`

**Comment by mihailescu2m** [comment]
`Requirement already satisfied: pycryptodome in /usr/local/lib/python2.7/dist-packages`

**Comment by trummerjo** [comment]
`pip install pycryptodomex`

**Comment by mihailescu2m** [comment]
For some reason, pycryptodome was installed in the Crypto folder, symlinking Cryptodome to Crypto in the above location worked.

**Comment by trummerjo** [comment]
pycryptodome always gets (per default) installed in the crypto folder.
Thats the reason why you need to install pycryptodomex

**Comment by domtik** [comment]
Use this Kodi version KodiSetup-20170809-67137d6348-master-x86.exe. It has a working cryptodomex library. The plugin is working great. All problems are related to Kodi nighty builds.
Check this step by step tutorial for windows:
https://domtik.com/index.php/2017/09/03/addon-netflix-kodi/

**Comment by montvid** [comment]
On linux Kodi it is not installed by default. please add pip install pycryptodomex to main readme.

**Comment by fbens** [comment]
```
Requirement already satisfied: pycryptodomex in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by thenextdon13** [comment]
To clarify the discussion from april 6th 2017;
pycryptodome and pycryptodomex are different packages; 
pycryptodome installs many files in /usr/local/lib/py/thon2.7/dist-packages/Crypto
pycryptodomex installs many files in /usr/local/lib/python2.7/dist-packages/Cryptodome

At one point, kodi changed the dependency from pycryptodome to pycryptodomex.  O rmy distribution had the dependency wrong to begin with

I believe my distribution didn't accuratly update the 'depends' listing for kodi when this happened, so i ended up with pycryptodome installed, when kodi expected pycryptodomex... so kodi was looking in the wrong folder for crypto

When the problem first occured, making the noted symlink functionally worked;  would have also worked to manually install pycryptodomex

However the symlink later broke the installation of pycryptodomex when the kodi dependency was fixed (due to conflicting files in filesystem).  Removing the symlink fixed that problem.
