### ISSUE TITLE
Request Error, Login Failed

### ISSUE THREAD

**Issue by gary9872** [asciidisco/plugin.video.netflix#398]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [YES ] Are you running the latest version?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Open up Netflix addon]

**Expected behavior: ** Bring me to the profiles page.

**Actual behavior:**  Does not open Netflix Addon.]

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

Core Elec 80.9.3
## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

https://pastebin.com/7TsRh5n5

**Comment by knappster1** [comment]
I'm getting the same messages, but my logs seem completely different.  I was on 0.13.7, so I updated to 0.13.8 with the same results.  The popups read:
"Request Error
Unable to complete the request at this time"
followed with
"Login Failed
Please Check your credentials"

I have tried logging out and back in.  I was able to watch a video yesterday evening, but I noticed that it began with the language in German instead of English so I had to switch audio tracks.  Seems like it would be totally unrelated, but due to the proximity in time, I thought it worth mentioning.

My log follows

https://pastebin.com/dHv182qC

**Comment by gb160** [comment]
I'm getting the same behaviour running 0.13.8 on the latest OSMC nightly.

**Comment by mattreecebentley** [comment]
This started again today.
I tried latest nightly, downloaded zip clone of repo, updated plugin from zip, still doesn't work.
BTW most stable nightly seems to be 03 June2018.

**Comment by liberty-developer** [comment]
@Dodobibi falkorCache is again not found with the regexp, also its in the content.
Do you have time to figure out what's going on there?

**Comment by liberty-developer** [comment]
nvm, netflix corrected a typo, last commit should solve the issue

**Comment by gb160** [comment]
Yep, fixed for me :)

**Comment by knappster1** [comment]
@liberty-developer thanks for the quick turnaround.  I'll try it out this evening.

**Comment by Dodobibi** [comment]
Fixed for me too :)
Ahhh, Netflix make us jokes!
