### ISSUE TITLE
Kodi crashes when trying to open a stream

### ISSUE THREAD

**Issue by aherking** [asciidisco/plugin.video.netflix#452]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
I have an Intel NUC System with Windows 10 x64. I tested the actual x64 and x86 build of Kodi, but the error is always the same.
### Prerequisites

* [x]Are you running the latest version?

### Description

When i try to open a stream with the plugin, the loading indicator is shown up but suddenly freeze and kodi crashes with a close. There is no error in the log which could explain it (in my eyes).
### Steps to Reproduce

1. Look for a Stream, doesnt matter if a TV Show or a Movie
2. Open it and wait for the crash

This error is since several month - I first ecountered it in with the first Alpha, but I switched back to Kodi 17 to wait still more stable . But now I think it's more an error in the plugin

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Intel NUC BOXNUC7I3BNH 
Windows 10 x64, Kodi 18 Alpha 3 x86 
## Debug log

`18:24:21.212 T:11836  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.netflix/?action=play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27writer%27%3A+%27%27%2C+%27episode%27%3A+1%2C+%27plot%27%3A+u%27Prinzessin+Bean+bl%5Cxe4st+an+ihrem+Hochzeitstag+Tr%5Cxfcbsal.+Pl%5Cxf6tzlich+erscheint+eine+r%5Cxe4tselhaft+Kreatur+und+stellt+sich+als+ihr+D%5Cxe4mon+vor.+Elfo+hasst+seine+gl%5Cxfcckliche+Heimat.%27%2C+%27season%27%3A+1%2C+%27tvshowtitle%27%3A+u%27Disenchantment%27%2C+%27title%27%3A+u%27Eine+Prinzessin%2C+ein+Elf+und+ein+D%5Cxe4mon+kommen+in+eine+Bar%27%2C+%27mediatype%27%3A+u%27episode%27%2C+%27mpaa%27%3A+u%27-%27%2C+%27director%27%3A+%27%27%2C+%27genre%27%3A+u%27Action-+und+Abenteuerserien%27%2C+%27year%27%3A+0%2C+%27duration%27%3A+2170%7D&video_id=80117711&pin=False&start_offset=-1
18:24:21.212 T:5600  NOTICE: Creating InputStream
18:24:23.897 T:5600  NOTICE: Creating Demuxer
18:24:23.899 T:5600  NOTICE: Opening stream: 1 source: 256
18:24:24.078 T:5600  NOTICE: Creating video codec with codec id: 27
18:24:24.081 T:5600  NOTICE: Creating video thread
18:24:24.081 T:12316  NOTICE: running thread: video_thread
18:24:24.081 T:5600  NOTICE: Opening stream: 3 source: 256
18:24:24.139 T:5600  NOTICE: Finding audio codec for: 86056
18:24:24.139 T:5600  NOTICE: Creating audio thread
18:24:24.140 T:5600  NOTICE: Opening stream: 14 source: 256
18:24:24.141 T:4128  NOTICE: running thread: CVideoPlayerAudio::Process()
18:24:24.423 T:4128  NOTICE: Creating audio stream (codec id: 86056, channels: 6, sample rate: 48000, pass-through)
18:24:28.939 T:12316 WARNING: CRenderManager::Configure - timeout waiting for configure
`
I can provide the crash dump if needed

**Comment by nickkindt** [comment]
Exactly the same issue here.
Same OS.

logs & crashdump provided here.

thx in advance,
Nick

[kodi.log](https://github.com/asciidisco/plugin.video.netflix/files/2325399/kodi.log)

[kodi_stacktrace-18.0-ALPHA3 Git_20180731-269a24c194-20180827-214610.txt](https://github.com/asciidisco/plugin.video.netflix/files/2325400/kodi_stacktrace-18.0-ALPHA3.Git_20180731-269a24c194-20180827-214610.txt)

**Comment by caphm** [comment]
@aherking please provide the full debug log, the excerpt doesn't help much.

@nickkindt please turn on debug logging in Kodi and provide the resulting debug log. The one you uploaded is missing debug output.

In both cases, since Kodi gets to the point to setup audio and video streams but then crashes, I suspect this to be an issue with Kodi itself and not the addon.
Does it happen with other video sources as well? (local, NFS/SMB, other addons)

Try
- updating your graphics card drivers
- selecting a different render method in Kodi
- starting from scratch with a clean Kodi install

**Comment by nickkindt** [comment]
Hey caphm,

The youtube add on & soundcloud addon works fine.
playing movies from smb shares also works fine.

Also started from scratch with x64 & x86 install (manually deleted kodi folders in program files & roaming directories), didn't help.

Changed redering method  for kodi player from "auto select" to "software". Problem solved.
I guess the onboard graphics of the intel i3 cpu isn't all that?
Is there any way to change only to software rendering for the kodi plugin?

thanks in advance,
Nick

[kodi.log](https://github.com/asciidisco/plugin.video.netflix/files/2328935/kodi.log)

**Comment by caphm** [comment]
That's odd, because the addon doesn't use hardware acceleration due to Netflix's license restricitons.
I'm using an Intel integrated GPU on an i5 and never had any issues. Maybe try some different (also older) driver versions. As far as I recall, there was a release a while back that caused me nothing but troubles, so I'm still running an older driver.

Unfortunately there's no way to define render settings for specific plugins/video sources. You'll have to go with software for everything.

Closing this, as it's an issue with your local Kodi / graphics card setup.
