### ISSUE TITLE
Support Up Next addon

### ISSUE THREAD

**Issue by im85288** [asciidisco/plugin.video.netflix#506]
*I'm submitting a ...*
  - [ ] bug report
  - [x] feature request
  - [ ] support request

## General information

Hi, I am the developer of the old Next Up addon and have recently created a new [Up Next](https://github.com/im85288/service.upnext/wiki) addon that [integrates ](https://github.com/im85288/service.upnext/wiki/Addon-Integration) with other video addons. 

Would you be interested in adding integration of this addon for episodes?

Thanks

**Comment by caphm** [comment]
Definitely. I'm working on a larger release and will integrate support.

**Comment by im85288** [comment]
Excellent thanks, 

Yes no problem at all, that sounds really cool being able to have the popup coming exactly when  the credits start. I also plan to add support for skipping the intro (as I know that data is available to netflix too) but that will come at a later stage. I'll add support for the notification time now and update the wiki.

**Comment by im85288** [comment]
I added [support](https://github.com/im85288/service.upnext/wiki/Data-to-Send) now. If there's any questions just let me know (as yet this is untested so there may be issues)

**Comment by caphm** [comment]
With Netflix there are two sections that can be skipped: intro and recap. This is already implemented in this addon, you can have a look at https://github.com/asciidisco/plugin.video.netflix/blob/master/resources/lib/playback/section_skipping.py and draw some inspiration.
In order for this to work, one needs the exact timecodes of when these sections start and end. I am currently not aware of any other streaming services besides Netflix that would provide those. If Netflix is in fact the only one, I think it's more convenient to stick with the implementation in the Netflix addon, because the implementation in your addon would only serve this single use case.

**Comment by im85288** [comment]
Thanks, Yes as far as I am aware it's only Netflix that gives this level of information but hopefully down the line we may get something similar from Amazon. It's not a priority but I may have a look at the code linked above to see if it is worth adding.

**Comment by im85288** [comment]
Closing as this is now integrated :)
