### ISSUE TITLE
pycryptodome installed but dependency not met

### ISSUE THREAD

**Issue by Chazzz** [asciidisco/plugin.video.netflix#563]
*I'm submitting a ...*
  - [x] bug report
  - [x] support request

## General infomration

See debug log.

### Description

00:21:06.916 T:139778384851392   DEBUG: CAddonInstaller: installing 'plugin.video.netflix' version '0.13.19' from repository 'repository.netflix'
00:21:06.921 T:139778234251008   DEBUG: CAddonInstallJob[plugin.video.netflix]: requires script.module.pycryptodome version 3.4.3 which is not available
00:21:06.921 T:139778234251008   ERROR: CAddonInstallJob[plugin.video.netflix]: The dependency on script.module.pycryptodome version 3.4.3 could not be satisfied.

### Steps to Reproduce

1. Ubuntu 18.10 sudo apt install kodi
2. pip install --user pycryptodomex && pip3 install --user pycryptodomex
3. Download & install repository.netflix-1.0.1.zip
4. Attempt to install plugin.video.netflix-0.13.19

### Additional Information

Is there any MVP to check/verify pycryptodome? It's probably not plugin.video.netflix's fault that kodi can't find the dependency but it's at minimum bad installation instructions.

**Comment by vikram-haridas** [comment]
I have the exact same issue. Logs say the dependencies are weird

**Comment by jakermx** [comment]
Go Settings::System::Add-ons click on Manage Dependencies and find Python Crypto Dome, since it comes with the system it is not an AddOn, it is caller now as Library

**Comment by Chazzz** [comment]
@jakermx Thanks for the help, The list on screen when I bring up Manage Dependencies is: AllMusic Scraper Library, fanart.tv Scraper Library, IMDB Scraper Library, MusicBrainz Scraper Library, Python Image Library, The Movie Database Scraper Library, TheAudioDb Scraper Library.

**Comment by jakermx** [comment]
Hi There,
If you read the installation note from this project main page this is what it saids
"Cryptdome python library (for Linux systems, install using pip install --user pycryptodomex as the user that will run Kodi)"

And then I saw your reproduce method, 

Ubuntu 18.10 sudo apt install kodi
pip install --user pycryptodomex && pip3 install --user pycryptodomex

So what it comes to my mind, is that you are runnig kodi.bin as root, because you ran the apt install with sudo, means it is calling the install of kodi as root, since I dont have ubuntu to test it, please share the results of ps -ef, in order to know which user is executing the kodi binary, if it is root, then you should run
sudo pip install --user pycryptodomex && sudo pip3 install --user pycryptodomex

**Comment by Chazzz** [comment]
@jakermx Ran the command suggested, kodi is not being executed by root.

**Comment by jakermx** [comment]
Just try running

pip install pycryptodomex

or

pip install --user pycryptodomex

dont use && blablabla...

**Comment by jakermx** [comment]
or try 
pip install pycryptodome
or 
pip install --user pycryptodome

**Comment by Chazzz** [comment]
Still doesn't show up in manage dependencies

$ pip show pycryptodomex
Name: pycryptodomex
Version: 3.7.2
Summary: Cryptographic library for Python
Home-page: https://www.pycryptodome.org
Author: Helder Eijs
Author-email: helderijs@gmail.com
License: BSD, Public Domain
Location: /home/\<username\>/.local/lib/python2.7/site-packages
Requires:

**Comment by jakermx** [comment]
Remove the X at the end...and try again

**Comment by Chazzz** [comment]
(by the way I was using && as shorthand, i seriously doubt that it would change the installation directory, for example)

FYI `python -m Crypto.SelfTest` and `python -m Cryptodome.SelfTest` both complete successfully.

**Comment by Chazzz** [comment]
Still no change in manage dependences

$ pip show pycryptodome
Name: pycryptodome
Version: 3.7.2
Summary: Cryptographic library for Python
Home-page: https://www.pycryptodome.org
Author: Helder Eijs
Author-email: helderijs@gmail.com
License: BSD, Public Domain
Location: /home/\<user\>/.local/lib/python2.7/site-packages
Requires:

**Comment by jakermx** [comment]
Try removing the repo, and installing from ZIP..

[plugin.video.netflix-master (0.13.21).zip](https://github.com/asciidisco/plugin.video.netflix/files/2638421/plugin.video.netflix-master.0.13.21.zip)

**Comment by Chazzz** [comment]
'inputstream.adaptive is missing' error message when trying to watch a show, but I have Kodi 18 so it's installed... or not...

$ kodi --version
17.6 Debian package version: 2:17.6+dfsg1-2ubuntu1 Media Center Kodi from Debian
Copyright (C) 2005-2013 Team Kodi from Debian - http://kodi.tv

**Comment by jakermx** [comment]
cat kodi.log... and share it please

**Comment by Chazzz** [comment]
Isn't it useless? I'm obviously running an unsupported version of Kodi.

**Comment by jakermx** [comment]
well, It will tell you what are you running, what is installed and what could be missing or faulty, I juyst wanna help, If you dont think it is useless, so I cannot do much with the info you have shared...

**Comment by MilhouseVH** [comment]
Not sure if this is the exact same issue, but just so that you are aware the `<dependency> is missing` message that you may see in the GUI when installing an addon (or reviewing the addon dependencies) [cannot be trusted](https://github.com/xbmc/xbmc/issues/14697), so you may see the "... is missing" message even though the dependency is installed, accessible and usable, in which case you can just ignore the bogus message.

Unless you really are missing the dependency, of course... :(

**Comment by jakermx** [comment]
It saids 
17.6 Debian package version: 2:17.6+dfsg1-2ubuntu1 Media Center Kodi from Debian

It should say 18.0 RC1 or somethinng

**Comment by Chazzz** [comment]
The obvious solution here is to install Kodi 18, which doesn't exist on ubuntu 18 currently, fun fact.

**Comment by jakermx** [comment]
Some (later) Ubuntu versions include Kodi built by Ubuntu themselves. If you have installed Ubuntu Kodi, please remove the packages "kodi kodi-bin kodi-data" before trying to install team-xbmc PPA packages.



1.2 Installing a development build
See also: Development builds
To install a beta/unstable version of Kodi you must first add the unstable repository, then install XBMC. Use ppa:team-xbmc/xbmc-nightly for nightly builds and ppa:team-xbmc/unstable for beta builds.

sudo add-apt-repository ppa:team-xbmc/xbmc-nightly
sudo apt-get update
sudo apt-get install kodi

**Comment by jakermx** [comment]
https://forum.kodi.tv/showthread.php?tid=329869&page=2

**Comment by Chazzz** [comment]
@jakermx couldn't have said it better myself. sudo apt autoremove also works to remove kodi-bin and kodi-data after manually removing kodi.

**Comment by Chazzz** [comment]
Um... yeah so I installed the nightly build and all my data transferred over and everything works now. FYI python crypto library is now listed in the manage dependencies directory as well. Thanks all for the help.

**Comment by TRON4R** [comment]
Can anybody help me here with installing the pycrypto, pycryptodome or pycryptodomex library on my QNAP QTS 4.4.3 ?
Because I installed it successfully, but the Netflix plugin is still throwing errors in the logile:
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named Cryptodome
                                            Traceback (most recent call last):

although pip show says this:
[~] # pip show pycryptodomex
Name: pycryptodomex
Version: 3.9.8
Summary: Cryptographic library for Python
Home-page: https://www.pycryptodome.org
Author: Helder Eijs
Author-email: helderijs@gmail.com
License: BSD, Public Domain, Apache
Location: /root/.local/lib/python3.8/site-packages
Requires:
Required-by:

My guess is that somehow KODI (or the Netflix plugin) is looking in a different place than where the Cryptodomex library is installed. I don't know if this is a result of the QNAP QTS being a very different Linux distribution or because the HD station of QNAP is running in a different environment than the base QNAP system or because QNAP runs everything in an account called "admin" instead of the usual "root".

Any ideas here?

**Comment by TRON4R** [comment]
Fixed it myself. The solution can be found at the bottom of this thread here:
[https://github.com/asciidisco/plugin.video.netflix/issues/665](https://github.com/asciidisco/plugin.video.netflix/issues/665)

You can jump directly to my post by using this link:
[https://github.com/asciidisco/plugin.video.netflix/issues/665#issuecomment-690382026](https://github.com/asciidisco/plugin.video.netflix/issues/665#issuecomment-690382026)
