### ISSUE TITLE
Background image not loading

### ISSUE THREAD

**Issue by 416eddie** [asciidisco/plugin.video.netflix#659]
*I'm submitting a ...*
  - bug report

### Prerequisites

* [x] Are you running the latest version?
Yes
### Description

[Description of the bug or feature]
I have 3 widgets set up on home screen to pull from Netflix and there is no background images showing. I am using the bingie Netflix skin, I have other widgets set up pulling from different Addons and they all show background images. 
### Steps to Reproduce
Load widgets in home screen

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
To have background images show on home screen for each show or movie
**Actual behavior:** [What actually happened]
No background pictures
## Context (Environment)
Mac mini OSX Mojave
Kodi 18.1
Titan Bingie v1
![A7A05FA1-AC7A-4027-B298-03D7A322512B](https://user-images.githubusercontent.com/47375914/55116644-603b0600-50be-11e9-86e5-0a535c23429a.jpeg)
![C60ECD24-1C1C-4EF4-BF6F-41FDAA008FAD](https://user-images.githubusercontent.com/47375914/55116645-603b0600-50be-11e9-85ad-f88c085828ee.jpeg)

Install from release page
Netflix repo

**Comment by 416eddie** [comment]
Forgot to add log file
https://paste.ubantu.com/p/9NFZWwRgxK/

**Comment by jakermx** [comment]
Cant open your log file, but I would like to suggest you, to delay the start of the widgets, hey are part of  skins, so they load pretty fast, and the netflix services dont, so That causes that behaivor, of maybe you would like to read something of the skin helper script, 
here

https://forum.kodi.tv/showthread.php?tid=235676

or here

https://github.com/kodi-community-addons/script.skin.helper.service

this is not Netflix addon related issue,  I would suggest you to close or transfer this issue to kodi skin developer, or if you are using libraries , to kodi developers...
