### ISSUE TITLE
Error after addon installation

### ISSUE THREAD

**Issue by arturdulewicz** [asciidisco/plugin.video.netflix#664]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [x] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

After installing Netflix repo and launching the addon im getting an error. I can't even login or change the credentials at addons settings.
Im getting an error right after the installation, after trying to launch the addon, and right after the RPI reboot.

### Steps to Reproduce

1. install netflix add-on on rpi3 osmc (fully updated)
2. open netflix add-on
3. error

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x] Raspberry Pi 3 OSMC 18.8-23

## Debug log

https://pastebin.com/gkZR1Zr5

**Comment by jakermx** [comment]
please share the compleate log file

**Comment by arturdulewicz** [comment]
> please share the compleate log file

https://pastebin.com/iLcwWpFr

**Comment by jakermx** [comment]
from Cryptodome.Random import get_random_bytes
ImportError: No module named Cryptodome.Random

try reinstalling script.module.pycryptodome or script.module.pycryptodomex

**Comment by jakermx** [comment]
In order to get our add-ons working correctly, we need to add some additional dependencies and their recommended packages.

sudo apt-get install python-pip python-crypto build-essential -y
sudo apt-get install python-all-dev python-setuptools python-wheel -y
sudo apt-get install python-crypto-dbg python-crypto-doc python-pip-whl -y

Now lets install our Python cryptography dependency.


pip install pycryptodomex

To make sure our add-ons are finding our pycryptodomex module, lets add a symbolic link to the location.


sudo ln -s /usr/lib/python2.7/dist-packages/Crypto /usr/lib/python2.7/dist-packages/Cryptodome

**Comment by arturdulewicz** [comment]
> In order to get our add-ons working correctly, we need to add some additional dependencies and their recommended packages.
> 
> sudo apt-get install python-pip python-crypto build-essential -y
> sudo apt-get install python-all-dev python-setuptools python-wheel -y
> sudo apt-get install python-crypto-dbg python-crypto-doc python-pip-whl -y
> 
> Now lets install our Python cryptography dependency.
> 
> pip install pycryptodomex
> 
> To make sure our add-ons are finding our pycryptodomex module, lets add a symbolic link to the location.
> 
> sudo ln -s /usr/lib/python2.7/dist-packages/Crypto /usr/lib/python2.7/dist-packages/Cryptodome

Works like a charm. Thank you so much!
